# Generated by Django 4.1.2 on 2022-11-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_tag_level_remove_tag_lft_remove_tag_rght_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=0, max_length=200),
        ),
    ]
