# Generated by Django 4.1.2 on 2022-11-04 18:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='direction',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingridients',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
