# Generated by Django 4.1.3 on 2022-11-18 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comment_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 17, 20, 59, 579132, tzinfo=datetime.timezone.utc)),
        ),
    ]
