# Generated by Django 4.1.3 on 2022-11-19 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 18, 24, 44, 698364, tzinfo=datetime.timezone.utc)),
        ),
    ]
